version: "3"

services:
  player:
    container_name: player
    image: reaciveapp/player
    build: ./player
    ports:
      - 8080:80

  playerApi:
    container_name: playerapi
    image: reactiveapp/playerapi
    build: ./playerApi
    ports:
      - "8082:3000"
    depends_on:
      - redis
    links:
      - redis

  hostApi:
    container_name: hostapi
    image: reactiveapp/hostapi
    build: ./hostApi
    ports:
      - "8081:9000"
    depends_on:
      - redis
    links:
      - redis

  redis:
    container_name: redis
    image: redis:alpine
    environment:
      - appendonly=yes
    volumes:
      - /etc/reacive-subsystems/redis:/data

networks: 
  default:
    external:
      name: reactive-subsystems